all:
  hosts:
    operations-1:
      ansible_host: 10.8.0.18
      ip: 10.8.0.18
      access_ip: 10.8.0.18
    operations-2:
      ansible_host: 10.8.0.51
      ip: 10.8.0.51
      access_ip: 10.8.0.51
    operations-3:
      ansible_host: 10.8.0.28
      ip: 10.8.0.28
      access_ip: 10.8.0.28
  children:
    kube-master:
      hosts:
        operations-1:
        operations-2:
    kube-node:
      hosts:
        operations-1:
        operations-2:
        operations-3:
    etcd:
      hosts:
        operations-1:
        operations-2:
        operations-3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}