all:
  hosts:
    node1:
      ansible_host: 10.8.0.18
      ip: 10.8.0.18
      access_ip: 10.8.0.18
    node2:
      ansible_host: 10.8.0.51
      ip: 10.8.0.51
      access_ip: 10.8.0.51
    node3:
      ansible_host: 10.8.0.28
      ip: 10.8.0.28
      access_ip: 10.8.0.28
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
