all:
  hosts:
    deployment-1:
      ansible_host: 10.8.0.18
      ip: 10.8.0.18
      access_ip: 10.8.0.18
    deployment-2:
      ansible_host: 10.8.0.51
      ip: 10.8.0.51
      access_ip: 10.8.0.51
    deployment-3:
      ansible_host: 10.8.0.28
      ip: 10.8.0.28
      access_ip: 10.8.0.28
  children:
    kube-master:
      hosts:
        deployment-1:
        deployment-2:
    kube-node:
      hosts:
        deployment-1:
        deployment-2:
        deployment-3:
    etcd:
      hosts:
        deployment-1:
        deployment-2:
        deployment-3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}