all:
  hosts:
    node1:
      ansible_host: 10.8.0.67
      ip: 10.8.0.67
      access_ip: 10.8.0.67
    node2:
      ansible_host: 10.8.0.17
      ip: 10.8.0.17
      access_ip: 10.8.0.17
    node3:
      ansible_host: 10.8.0.48
      ip: 10.8.0.48
      access_ip: 10.8.0.48
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}