---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    volume: nfs-volume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    server: 172.17.8.104
    path: "/nfs"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      volume: nfs-volume
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nfs-test
  # labels so that we can bind a service to this pod
  labels:
    app: nfs-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nfs-test
  template:
    metadata:
      labels:
        app: nfs-test
    spec:
      containers:
      - name: nfs-test
        image: busybox
        command: [ 'sh', '-c', 'date >> /tmp/date && sleep 3600' ]
        volumeMounts:
          - name: nfs-test
            mountPath: "/tmp"
      volumes:
      - name: nfs-test
        persistentVolumeClaim:
          claimName: nfs-pvc
      securityContext:
        runAsUser: 65534
        fsGroup: 65534