all:
  hosts:
    deployment-1:
      ansible_host: 10.8.0.67
      ip: 10.8.0.67
      access_ip: 10.8.0.67
    deployment-2:
      ansible_host: 10.8.0.17
      ip: 10.8.0.17
      access_ip: 10.8.0.17
    deployment-3:
      ansible_host: 10.8.0.48
      ip: 10.8.0.48
      access_ip: 10.8.0.48
  children:
    kube-master:
      hosts:
        deployment-1:
        deployment-2:
    kube-node:
      hosts:
        deployment-1:
        deployment-2:
        deployment-3:
    etcd:
      hosts:
        deployment-1:
        deployment-2:
        deployment-3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}